version: '3.8' 
services: 
backend: build: ./backend 
container_name: my_backend 
ports: 
- "8000:8000" 
restart: always 

frontend: 
build: ./frontend 
container_name: my_frontend 
ports: 
- "3000:80" 
restart: always

